const { v4: uuidv4 } = require("uuid");

let users = [
  {
    id: uuidv4(),
    name: "John",
    gender: "Male",
    contact: "(489) 330-2385",
    address: "XYZ Street",
    photoURL: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: uuidv4(),
    name: "David",
    gender: "Male",
    contact: "(489) 330-2385",
    address: "XYZ Street",
    photoURL: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: uuidv4(),
    name: "Paul",
    gender: "Male",
    contact: "(489) 330-2385",
    address: "XYZ Street",
    photoURL: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: uuidv4(),
    name: "Tom",
    gender: "Male",
    contact: "(489) 330-2385",
    address: "XYZ Street",
    photoURL: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: uuidv4(),
    name: "Smith",
    gender: "Male",
    contact: "(489) 330-2385",
    address: "XYZ Street",
    photoURL: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: uuidv4(),
    name: "Jennie",
    gender: "Female",
    contact: "(489) 330-2385",
    address: "ABC Street",
    photoURL: "https://randomuser.me/api/portraits/thumb/women/91.jpg",
  },
  {
    id: uuidv4(),
    name: "Olivia",
    gender: "Female",
    contact: "(489) 330-2385",
    address: "ABC Street",
    photoURL: "https://randomuser.me/api/portraits/thumb/women/91.jpg",
  },
  {
    id: uuidv4(),
    name: "Ellie",
    gender: "Female",
    contact: "(489) 330-2385",
    address: "ABC Street",
    photoURL: "https://randomuser.me/api/portraits/thumb/women/91.jpg",
  },
  {
    id: uuidv4(),
    name: "Anna",
    gender: "Female",
    contact: "(489) 330-2385",
    address: "ABC Street",
    photoURL: "https://randomuser.me/api/portraits/thumb/women/91.jpg",
  },
  {
    id: uuidv4(),
    name: "julia",
    gender: "Female",
    contact: "(489) 330-2385",
    address: "ABC Street",
    photoURL: "https://randomuser.me/api/portraits/thumb/women/91.jpg",
  },
];

module.exports = users;
